version: '3.6'

services:
  postgres:
    image: postgres:12
    restart: always
    container_name: sorarium-postgres
    environment:
      POSTGRES_USER: sorarium-admin
      POSTGRES_PASSWORD: sorarium-password
      POSTGRES_DB: sorarium
    ports:
      - 5434:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
